// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoolApp.Data;

#nullable disable

namespace PoolApp.Migrations
{
    [DbContext(typeof(PoolAppContext))]
    [Migration("20250323064418_init migration")]
    partial class initmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PoolApp.Models.Pool", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("alkalinityLevel")
                        .HasColumnType("int");

                    b.Property<int>("chlorineLevel")
                        .HasColumnType("int");

                    b.Property<string>("client")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("nextServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("recentServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("recentVac")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Pool");
                });
#pragma warning restore 612, 618
        }
    }
}
